### ISSUE TITLE
Error when passing in TTFont with integer version

### ISSUE THREAD

**Issue by NightFurySL2001** [robotools/extractor#59]
When using `fontBuilder` to generate a font and overriding the version number in `head` by providing an integer value, passing the TTFont into extractor class raises an error.

Minimal reproduce code:
```py
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.t2CharStringPen import T2CharStringPen

from ufoLib2 import Font as UFOFont
from extractor.formats.opentype import (
    extractOpenTypeInfo,
    extractOpenTypeGlyphs,
    extractGlyphOrder,
)

# provided minimal OTF build in fontBuilder
def drawTestGlyph(pen):
    pen.moveTo((100, 100))
    pen.lineTo((100, 1000))
    pen.curveTo((200, 900), (400, 900), (500, 1000))
    pen.lineTo((500, 100))
    pen.closePath()


fb = FontBuilder(1024, isTTF=False)
fb.setupGlyphOrder([".notdef", ".null", "space", "A", "a"])
fb.setupCharacterMap({32: "space", 65: "A", 97: "a"})
advanceWidths = {".notdef": 600, "space": 500, "A": 600, "a": 600, ".null": 0}

familyName = "HelloTestFont"
styleName = "TotallyNormal"
version = "1"

nameStrings = dict(
    familyName=dict(en=familyName, nl="HalloTestFont"),
    styleName=dict(en=styleName, nl="TotaalNormaal"),
    uniqueFontIdentifier="fontBuilder: " + familyName + "." + styleName,
    fullName=familyName + "-" + styleName,
    psName=familyName + "-" + styleName,
    version="Version " + version,
)

pen = T2CharStringPen(600, None)
drawTestGlyph(pen)
charString = pen.getCharString()
charStrings = {
    ".notdef": charString,
    "space": charString,
    "A": charString,
    "a": charString,
    ".null": charString,
}
fb.setupCFF(nameStrings["psName"], {"FullName": nameStrings["psName"]}, charStrings, {})
lsb = {gn: cs.calcBounds(None)[0] for gn, cs in charStrings.items()}
metrics = {}
for gn, advanceWidth in advanceWidths.items():
    metrics[gn] = (advanceWidth, lsb[gn])
fb.setupHorizontalMetrics(metrics)
fb.setupHorizontalHeader(ascent=824, descent=200)
fb.setupNameTable(nameStrings)
fb.setupOS2(sTypoAscender=824, usWinAscent=824, usWinDescent=200)
fb.setupPost()

# overriding font revision number
fb.setupHead(fontRevision=1)

# output to ufo, shoudln't be a problem with using ufoLib2 right?
outputpath = "test.ufo"
ttfont = fb.font
destination = UFOFont()
extractOpenTypeInfo(ttfont, destination)
extractOpenTypeGlyphs(ttfont, destination)
extractGlyphOrder(ttfont, destination)
destination.save(outputpath)
```

Error:
```
Traceback (most recent call last):
  File "d:\Desktop\coding\svg2font\testbuildbug.py", line 66, in <module>
    extractOpenTypeInfo(ttfont, destination)
  File "D:\Desktop\coding\svg2font\kivy_venv\lib\site-packages\extractor\formats\opentype.py", line 231, in extractOpenTypeInfo
    _extractInfoHead(source, info)
  File "D:\Desktop\coding\svg2font\kivy_venv\lib\site-packages\extractor\formats\opentype.py", line 245, in _extractInfoHead
    versionMajor, versionMinor = version.split(".")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by benkiel** [comment]
If you pass `1.0` it should work, it expects a a decimal to split; as the head table needs a version major and a version minor.

**Comment by benkiel** [comment]
In other words, passing an integer is a bug in your demo code, not extractor; it should give a `ValueError` here

**Comment by NightFurySL2001** [comment]
I see. fontBuilder does allow integer value though when saving the font file as OTF.

**Comment by benkiel** [comment]
@NightFurySL2001 you might want to open a issue or PR for fontBuilder, it should convert an integer value to float if given an integer.
